### ISSUE TITLE
ffi gem breaking on osx GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cc#122] opened 2020-11-09 13:51 UTC
This has hit quite suddenly, 2 hours ago:

https://github.com/metanorma/metanorma-itu/actions/runs/353863151
https://github.com/metanorma/metanorma-nist/actions/runs/353868442
https://github.com/metanorma/metanorma-ogc/actions/runs/353869297
https://github.com/metanorma/metanorma-cc/actions/runs/353865502

These are breaking OSX GHA. I am not getting this breakage in my local environment. The complaint is that sassc is not finding the local gem 2.x/ffi, where 2.x is the Ruby version

This issue is reported in:

https://medium.com/@hisa_py/jekyll-with-asdf-ruby-fix-ruby-ffi-loaderror-on-macos-high-sierra-c302f0567e9b , https://talk.jekyllrb.com/t/help-with-jekyll-error/3828/8 , 
https://talk.jekyllrb.com/t/jekyll-fails-on-macos-catalina/3765/8 > https://github.com/sass/sassc-ruby/issues/146

**Comment by CAMOBAP** [comment] 2021-07-24 11:55
@opoudjis it looks like the issue is gone, I propose to close it if there now cases for this issue

**Closed** 2021-07-27 09:22 UTC
Labels: bug
